<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>ShopingStore.Web</RootNamespace>
    <AssemblyName>ShopingStore.Web</AssemblyName>
    <UserSecretsId>shopstore-web-2026</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShopingStore.Domain\ShopingStore.Domain.csproj" />
    <ProjectReference Include="..\ShopingStore.Infrastructure\ShopingStore.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\products\" />
    <Folder Include="wwwroot\img\categories\" />
  </ItemGroup>

</Project>
